# /**
#  * GitHub Actions workflow to run code formatting on pull requests.
#  *
#  * Triggers on closed pull requests targeting the main branch. Checks out the repo,
#  * sets up the Node.js environment, installs dependencies, runs formatting, and fails if
#  * there are lint errors.
#  */

name: Format code

on:
  schedule:
    #only run every seven days
    - cron: "0 0 * * */5" # At 00:00 every 7th day

jobs:
  format-code:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - uses: actions/checkout@v4 # Checkout the repository code
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4 # Set up Node.js environment
        with:
          node-version: 20 # Specify the Node.js version

      - run: npm ci # Install dependencies
      - run: npx prettier --write ./src # Execute the formatting command
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(prettier): beautify code"
          branch: main
