name: Linter
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install all packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
